### PR TITLE
export required icons

### PR DESCRIPTION
**Pull request by Scharps**
I've made an attempt to allow for sole use of individual icons. Apologies for any errors in this pull request, it is my first :)

### CODE REVIEW

**Comment by romgrk** [comment]
Hey, thanks for the work! However I don't think this approach is quite right, this is not DRY enough. At the very least, I would rather expect to have a nodejs script that could be run at build time to read the icons directory and generate those files automagically rather than having the files in themselves. I haven't looked yet at how icon packages do their export but it would be nice to do so also.

This is to ensure that we don't avoid to manually modify things everytime there is a change.
Btw I haven't listed it but I was thinking about renaming or adding additional aliases for icons to having something closer to [this](https://fontawesome.com/v4.7.0/icons/). Some names are not well chosen, eg `emblem-ok` can be renamed to `check` and `list-add/list-remove` can be renamed to `add/close`.

**Comment by romgrk** [comment]
My two concerns here are:
 - bundle size when using the icons
 - DX when coding

The "ideal" solution would be to be able to use icons simply as doing `<Icon name='xxxx' />` rather than having to `import Xxxx from 'icons/xxxx` everytime an icon is needed, but that those usages be transpiled at build time into their single-import-per-icon form.

**Comment by Scharps** [comment]
The files were created using a C# script, I'll work on converting this to a JS alternative. The material-ui icon package has individual components for each icon to keep the size of individual imports down. Importing the existing Icon definition would import all variants, or does webpack have a way to avoid this?

Renaming or aliasing icons could be done with an exception definition.

**Comment by romgrk** [comment]
> Importing the existing Icon definition would import all variants, or does webpack have a way to avoid this?

If things are set up correctly webpack can tree-shake some things.

Relevant discussions:
 - https://github.com/palantir/blueprint/issues/2193
 - https://github.com/react-icons/react-icons/issues/154
 - https://github.com/react-icons/react-icons/issues/387

**Comment by romgrk** [comment]
Is this ready? If so can you fix the App.js conflict?

It's fine if it's not perfect, we can adjust the rest later.

**Comment by Scharps** [comment]
The conflicts are resolved, just needs an appropriate build script command in package.json

**Comment by romgrk** [comment]
Ok, I'll merge as it is, we'll add the command later I need to add a build step for icons as well.

**Comment by romgrk** [comment]
Thanks :)

**Pull request merged**
